const ROLES = {
  ADMIN_GENERAL: 'ADMIN_GENERAL',
  JEFE: 'JEFE',
  ADMIN_RRHH: 'ADMIN_RRHH',
  TRABAJADOR: 'TRABAJADOR',
};

const ROLE_CREATION_RULES = {
  ADMIN_GENERAL: [ROLES.JEFE],
  JEFE: [ROLES.ADMIN_RRHH],
  ADMIN_RRHH: [ROLES.TRABAJADOR],
};

const TIME_EVENT_TYPES = ['CLOCK_IN', 'CLOCK_OUT', 'BREAK_START', 'BREAK_END'];

const VACATION_STATUSES = ['PENDING', 'APPROVED', 'REJECTED'];

module.exports = {
  ROLES,
  ROLE_CREATION_RULES,
  TIME_EVENT_TYPES,
  VACATION_STATUSES,
};
